# Generated by Django 3.2.4 on 2021-07-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_type',
            field=models.CharField(blank=True, choices=[('IMG', 'Foto xabar'), ('VED', 'Video xabar'), ('ACT', 'Dolzarb xabar')], default='Default', max_length=10, null=True, verbose_name='Post Turi'),
        ),
    ]
