# Generated by Django 3.2.4 on 2021-07-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210702_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='content_mini',
            field=models.CharField(default=1, max_length=150, verbose_name='Content post mini'),
            preserve_default=False,
        ),
    ]
