# Generated by Django 3.2.4 on 2021-07-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210702_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(blank=True, to='post.Tag', verbose_name='Tag'),
        ),
    ]
