# Generated by Django 3.2.4 on 2021-07-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_posts_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='views_post',
        ),
        migrations.AddField(
            model_name='posts',
            name='views_post',
            field=models.ManyToManyField(blank=True, related_name='post_view', to='post.IpModel'),
        ),
    ]
