# Generated by Django 3.2.4 on 2021-07-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20210704_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='actual_post',
            field=models.BooleanField(blank=True, null=True, verbose_name='Dolzarb xabar'),
        ),
        migrations.AddField(
            model_name='posts',
            name='photo_post',
            field=models.BooleanField(blank=True, null=True, verbose_name='Foto xabar'),
        ),
        migrations.AddField(
            model_name='posts',
            name='video_post',
            field=models.BooleanField(blank=True, null=True, verbose_name='Video xabar'),
        ),
    ]
