# Generated by Django 3.2.4 on 2021-07-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConatacUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Исм-Фамиля*')),
                ('e_pochta', models.EmailField(max_length=250, verbose_name='Эл.Почта*')),
                ('subject', models.CharField(max_length=250, verbose_name='Мавзу')),
                ('message', models.TextField(verbose_name='Ҳабар')),
            ],
        ),
    ]
