# Generated by Django 3.2.4 on 2021-07-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contac_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conatacus',
            name='phone',
            field=models.CharField(default=1, max_length=250, verbose_name='Телефон*'),
            preserve_default=False,
        ),
    ]
